services:
  generator:
    image: tensorflow/serving:latest  # Use TensorFlow Serving image
    container_name: generator_serving
    volumes:
      - ./Model/ACGAN_Gen_SavedModel/1:/models/generator/1  # Model directory with versioning
    environment:
      - MODEL_NAME=generator  # Specify model name to TensorFlow Serving
    ports:
      - "8501:8501"  # Expose TensorFlow Serving port for the generator model
    networks:
      - acgan_network

  discriminator:
    image: tensorflow/serving:latest  # Use TensorFlow Serving image
    container_name: discriminator_serving
    volumes:
      - ./Model/ACGAN_Disc_SavedModel/1:/models/discriminator/1  # Model directory with versioning
    environment:
      - MODEL_NAME=discriminator  # Specify model name to TensorFlow Serving
    ports:
      - "8502:8501"  # Expose TensorFlow Serving port for the discriminator model
    networks:
      - acgan_network

networks:
  acgan_network:
    driver: bridge