services:
  generator:
    image: tensorflow/serving:latest  
    container_name: generator_serving
    volumes:
      - ./Model/ACGAN_Gen_SavedModel/1:/models/generator/1 
    environment:
      - MODEL_NAME=generator 
    ports:
      - "8501:8501" 
    networks:
      - acgan_network

  discriminator:
    image: tensorflow/serving:latest  
    container_name: discriminator_serving
    volumes:
      - ./Model/ACGAN_Disc_SavedModel/1:/models/discriminator/1  
    environment:
      - MODEL_NAME=discriminator 
    ports:
      - "8502:8501" 
    networks:
      - acgan_network

networks:
  acgan_network:
    driver: bridge